'use strict';

// Generated by `docgov init`, then customized by hand — see
// docs/org-governance-adoption.md for the policy this file enforces
// mechanically.
//
// This config declares DATA, never logic. If you need a check that doesn't
// exist, it belongs in the engine (licorsy/docs-governance), not here —
// otherwise the engine ends up forked-by-config and duplication sneaks back
// in through the side door.

// Every rule accepts a `why` field, printed when it fails. Fill it with the
// REAL defect that motivated the rule. A rule with no real defect shouldn't
// exist.

module.exports = {
  engine: '^1',

  rules: {
    frontmatter: {
      // Org-wide decision: every Markdown file carries the schema, so the
      // corpus is machine-enumerable and retrieval-ready. The exceptions
      // below are not preferences — each one would break another system's
      // parsing or rendering:
      //
      //   README.md  is rendered as the public organization profile at
      //              github.com/licorsy, and GitHub renders frontmatter as a
      //              visible table. It is excluded from `root_files` and
      //              carries no frontmatter, so it declares no id either.
      //
      //   .github/PULL_REQUEST_TEMPLATE.md and .github/ISSUE_TEMPLATE/*.md
      //              are owned by GitHub: the first is injected verbatim into
      //              every PR body, the second carries GitHub's own template
      //              frontmatter (name/about/title/labels). Neither is in
      //              scope here, since `scope_dirs` covers docs/ only and
      //              `root_files` is an explicit list.
      //
      //   agents/, commands/, .claude/agents/, .claude/commands/
      //              are Claude Code plugin manifests, where frontmatter is
      //              the routing contract rather than documentation. They are
      //              exempt from THIS schema, not from checking: sibling repos
      //              (git-governance, docs-governance) scope these directories
      //              and enforce `description` alone, because that is the one
      //              field Claude Code actually routes on. None exist in this
      //              repository today; the exemption is stated so it stays
      //              true if any are added.
      //
      //   CHANGELOG.md
      //              follows Keep a Changelog, an external format standard
      //              that owns the file's structure. None exists here yet;
      //              stated so the register stays complete org-wide.
      //
      //   local-notes/**
      //              is git-untracked reference material, outside the governed
      //              corpus entirely. It is out of `frontmatter` scope for the
      //              same reason as anything untracked, and additionally
      //              excluded from `internal-links` by directory name below,
      //              because its links point at assets never copied here.
      //
      // CLAUDE.md and AGENTS.md are NOT exceptions — they are entry points,
      // but no other system owns their frontmatter and nothing renders them
      // verbatim, so they carry the schema like any other document. AGENTS.md
      // is the source of truth of the two; CLAUDE.md imports it with `@AGENTS.md`
      // and states nothing itself. Both are still governed here, because the
      // frontmatter is what puts them in the corpus at all.
      scope_dirs: ['docs'],
      root_files: [
        'AGENTS.md',
        'CLAUDE.md',
        'GOVERNANCE.md',
        'CONTRIBUTING.md',
        'SECURITY.md',
        'SUPPORT.md',
        'CODE_OF_CONDUCT.md',
        'ARCHITECTURE-PRINCIPLES.md',
        'ENGINEERING-STANDARDS.md',
        'REPOSITORY-CLASSIFICATION.md',
        'SECURITY-BASELINE.md',
      ],
      exclude_prefixes: [],
      // Empty by design: the only unvalidated root file is README.md, and it
      // carries no frontmatter at all, so it declares no id to resolve.
      id_only_sources: [],
      required: ['title', 'doc_type', 'description', 'status', 'version', 'created', 'updated', 'language'],
      status_enum: ['draft', 'active', 'deprecated', 'archived'],
      doc_type_enum: [
        'instruction', 'manual', 'prompt', 'template', 'tool-catalog',
        'governance', 'adr', 'status-artifact', 'product-doc', 'spec-kit-artifact',
      ],
      date_fields: ['created', 'updated'],
      why: 'the schema is what makes the corpus machine-enumerable; resolving '
        + '`related:` is cross-file and is what keeps the reference graph honest '
        + 'as documents are added and renamed',
    },

    'internal-links': {
      // prunes by directory NAME, at any depth. `local-notes` holds
      // git-untracked reference material (see SECURITY.md) whose links point
      // at assets that were never copied here — excluding it is why that
      // material lives in a directory rather than at the repo root.
      exclude_dir_names: ['.git', 'node_modules', '.vscode', 'local-notes'],
      skip_link_patterns: [],
      why: 'the governance documents cross-reference each other heavily and all '
        + 'name the blueprint as canonical source; a rename that breaks one of '
        + 'those links silently breaks the traceability the whole set relies on',
    },

    'changelog-retention': {
      // Scoped to exactly the same corpus as `frontmatter`. The blueprint is
      // the one document here carrying a body changelog; the rule is a no-op
      // for the rest, which have no marker line.
      //
      // The marker below must match the heading line EXACTLY — the engine
      // compares `line.trim() === marker`, so "Changelog of this document:"
      // (the convention in ai-assisted-sdd-template) would be silently
      // skipped rather than flagged. That is precisely how the blueprint's
      // changelog went unchecked when it was first added.
      scope_dirs: ['docs'],
      root_files: [
        'AGENTS.md',
        'CLAUDE.md',
        'GOVERNANCE.md',
        'CONTRIBUTING.md',
        'SECURITY.md',
        'SUPPORT.md',
        'CODE_OF_CONDUCT.md',
        'ARCHITECTURE-PRINCIPLES.md',
        'ENGINEERING-STANDARDS.md',
        'REPOSITORY-CLASSIFICATION.md',
        'SECURITY-BASELINE.md',
      ],
      exclude_prefixes: [],
      exclude_files: [],
      marker: 'Changelog:',
      max_entries: 3,
      why: 'unbounded in-body changelogs are what pushed the real history out of '
        + 'reach in sibling repositories — the newest three belong in the file, '
        + 'the rest belongs to `git log --follow`',
    },

    'version-bump': {
      // Every governed document carries `version:`, so editing one without
      // bumping it is now a detectable defect rather than a matter of memory.
      enabled: true,
    },

    // ---- Phase 2+ content rules ----
    // Each entry exists to pin a fact that has ALREADY drifted in this
    // repository — adding entries speculatively is how a config turns into
    // logic. `sum_decomposition`, `version_citations`, `dead_citations` and
    // `sync_destinations` stay inert for exactly that reason: no real defect
    // has motivated them here yet.
    facts: {
      // NOT shadow. `facts` ships shadow-on by default, which means it reports
      // and never fails. A pin that cannot fail the build is decoration, and
      // decoration is what let all three of these drift in the first place.
      // Turning it off also makes the rule run under `--changed`, so
      // pre-commit catches the drift instead of CI at promotion time.
      shadow: false,
      scope_dirs: ['docs'],
      root_files: ['AGENTS.md', 'CLAUDE.md', 'REPOSITORY-CLASSIFICATION.md'],
      entries: [
        {
          id: 'governance-compliance-artifacts',
          value: 'AGENTS.md, CLAUDE.md, .pre-commit-config.yaml, '
            + '.github/workflows/pr-checks.yml, .docgov.config.js, .claude/settings.json',
          why: 'the definition of "compliant" is what /git-check, the adoption '
            + 'runbook, and platform-workflows\' governance-compliance.yml all work '
            + 'from; the list has already changed TWICE in one day '
            + '(.claude/settings.json, then AGENTS.md) and nothing but this entry '
            + 'checks that every place stating it moved together',
          required_in: [
            {
              file: 'docs/org-governance-adoption.md',
              pattern: /`AGENTS\.md`[\s\S]*?`CLAUDE\.md`[\s\S]*?`\.pre-commit-config\.yaml`[\s\S]*?`\.github\/workflows\/pr-checks\.yml`[\s\S]*?`\.docgov\.config\.js`[\s\S]*?`\.claude\/settings\.json`/,
            },
            { file: 'AGENTS.md', pattern: /six compliance artifacts/ },
          ],
        },
        {
          id: 'frontmatter-exceptions-register',
          value: 'README.md, .github/PULL_REQUEST_TEMPLATE.md, .github/ISSUE_TEMPLATE/*.md, '
            + 'agents+commands plugin manifests, CHANGELOG.md, local-notes/**',
          why: 'this register is stated twice on purpose — once as the comment above, '
            + 'once as a table in the runbook — and the two had already diverged: the '
            + 'comment omitted local-notes/** entirely and both described the plugin-'
            + 'manifest directories as unchecked when sibling repos do check them',
          required_in: [
            {
              file: '.docgov.config.js',
              pattern: /README\.md[\s\S]*?PULL_REQUEST_TEMPLATE\.md[\s\S]*?ISSUE_TEMPLATE[\s\S]*?commands\/[\s\S]*?CHANGELOG\.md[\s\S]*?local-notes/,
            },
            {
              file: 'docs/org-governance-adoption.md',
              pattern: /README\.md[\s\S]*?PULL_REQUEST_TEMPLATE\.md[\s\S]*?ISSUE_TEMPLATE[\s\S]*?commands\/\*\.md[\s\S]*?CHANGELOG\.md[\s\S]*?local-notes/,
            },
          ],
        },
        {
          id: 'merge-method-policy',
          value: 'develop: merge commit, squash | staging, main: merge commit only',
          why: 'per-branch allowed_merge_methods is the one setting that structurally '
            + 'prevents a squashed promotion from forking staging off develop; it is '
            + 'stated as policy here and applied by git-governance\'s '
            + 'setup-branch-protection.sh, so the copy an operator reads and the copy '
            + 'a script applies can silently disagree',
          required_in: [
            {
              file: 'AGENTS.md',
              // Both cells are anchored on their closing `|`. Without that, the
              // pattern matched a cell reading "merge commit, squash, rebase"
              // as a prefix match and the pin silently passed — caught by
              // deliberately breaking it rather than by trusting it.
              pattern: /`develop`\s*\|\s*merge commit, squash\s*\|[\s\S]*?`staging`, `main`\s*\|\s*merge commit only\s*\|/,
            },
            {
              file: 'docs/org-governance-adoption.md',
              // Both cells are anchored on their closing `|`. Without that, the
              // pattern matched a cell reading "merge commit, squash, rebase"
              // as a prefix match and the pin silently passed — caught by
              // deliberately breaking it rather than by trusting it.
              pattern: /`develop`\s*\|\s*merge commit, squash\s*\|[\s\S]*?`staging`, `main`\s*\|\s*merge commit only\s*\|/,
            },
          ],
          // the pre-2026-08-01 state: every branch accepting every method
          forbidden: [/allowed_merge_methods.*\[\s*["']merge["'],\s*["']squash["'],\s*["']rebase["']\s*\]/],
        },
        {
          id: 'commit-msg-lint-skips-merges',
          value: 'git log --no-merges --format=%s',
          why: 'without --no-merges the Conventional Commits check lints the '
            + '"Merge pull request #N from ..." subjects GitHub generates itself, '
            + 'which can never conform — so it fails by construction on every '
            + 'develop -> staging promotion, the exact PR it exists to guard. '
            + 'This repository shipped the broken form until 2026-08-01, with '
            + 'three such subjects already sitting in its promotion range',
          required_in: [
            {
              file: '.github/workflows/pr-checks.yml',
              pattern: /git log --no-merges --format=%s/,
            },
          ],
        },
      ],
    },
  },
};
