'use strict';

// Generated by `docgov init`, then customized by hand — see
// docs/org-governance-adoption.md for the policy this file enforces
// mechanically.
//
// This config declares DATA, never logic. If you need a check that doesn't
// exist, it belongs in the engine (licorsy/docs-governance), not here —
// otherwise the engine ends up forked-by-config and duplication sneaks back
// in through the side door.

// Every rule accepts a `why` field, printed when it fails. Fill it with the
// REAL defect that motivated the rule. A rule with no real defect shouldn't
// exist.

module.exports = {
  engine: '^1',

  rules: {
    frontmatter: {
      // Org-wide decision: every Markdown file carries the schema, so the
      // corpus is machine-enumerable and retrieval-ready. The exceptions
      // below are not preferences — each one would break another system's
      // parsing or rendering:
      //
      //   README.md  is rendered as the public organization profile at
      //              github.com/licorsy, and GitHub renders frontmatter as a
      //              visible table. It is excluded from `root_files` and
      //              carries no frontmatter, so it declares no id either.
      //
      //   .github/PULL_REQUEST_TEMPLATE.md and .github/ISSUE_TEMPLATE/*.md
      //              are owned by GitHub: the first is injected verbatim into
      //              every PR body, the second carries GitHub's own template
      //              frontmatter (name/about/title/labels). Neither is in
      //              scope here, since `scope_dirs` covers docs/ only and
      //              `root_files` is an explicit list.
      //
      //   agents/, commands/, .claude/agents/, .claude/commands/
      //              would be Claude Code plugin manifests, where frontmatter
      //              is the routing contract rather than documentation. None
      //              exist in this repository today; the exclusion is stated
      //              so it stays true if any are added.
      //
      //   CHANGELOG.md
      //              follows Keep a Changelog, an external format standard
      //              that owns the file's structure. None exists here yet;
      //              stated so the register stays complete org-wide.
      //
      // CLAUDE.md and AGENTS.md are NOT exceptions — they are entry points,
      // but no other system owns their frontmatter and nothing renders them
      // verbatim, so they carry the schema like any other document.
      scope_dirs: ['docs'],
      root_files: [
        'CLAUDE.md',
        'GOVERNANCE.md',
        'CONTRIBUTING.md',
        'SECURITY.md',
        'SUPPORT.md',
        'CODE_OF_CONDUCT.md',
        'ARCHITECTURE-PRINCIPLES.md',
        'ENGINEERING-STANDARDS.md',
        'REPOSITORY-CLASSIFICATION.md',
        'SECURITY-BASELINE.md',
      ],
      exclude_prefixes: [],
      // Empty by design: the only unvalidated root file is README.md, and it
      // carries no frontmatter at all, so it declares no id to resolve.
      id_only_sources: [],
      required: ['title', 'doc_type', 'description', 'status', 'version', 'created', 'updated', 'language'],
      status_enum: ['draft', 'active', 'deprecated', 'archived'],
      doc_type_enum: [
        'instruction', 'manual', 'prompt', 'template', 'tool-catalog',
        'governance', 'adr', 'status-artifact', 'product-doc', 'spec-kit-artifact',
      ],
      date_fields: ['created', 'updated'],
      why: 'the schema is what makes the corpus machine-enumerable; resolving '
        + '`related:` is cross-file and is what keeps the reference graph honest '
        + 'as documents are added and renamed',
    },

    'internal-links': {
      // prunes by directory NAME, at any depth. `local-notes` holds
      // git-untracked reference material (see SECURITY.md) whose links point
      // at assets that were never copied here — excluding it is why that
      // material lives in a directory rather than at the repo root.
      exclude_dir_names: ['.git', 'node_modules', '.vscode', 'local-notes'],
      skip_link_patterns: [],
      why: 'the governance documents cross-reference each other heavily and all '
        + 'name the blueprint as canonical source; a rename that breaks one of '
        + 'those links silently breaks the traceability the whole set relies on',
    },

    'changelog-retention': {
      // Scoped to exactly the same corpus as `frontmatter`. No document here
      // maintains a body changelog today, and the rule is a no-op for files
      // without the marker — so this scope imposes nothing now and starts
      // checking automatically if one is ever added.
      scope_dirs: ['docs'],
      root_files: [
        'CLAUDE.md',
        'GOVERNANCE.md',
        'CONTRIBUTING.md',
        'SECURITY.md',
        'SUPPORT.md',
        'CODE_OF_CONDUCT.md',
        'ARCHITECTURE-PRINCIPLES.md',
        'ENGINEERING-STANDARDS.md',
        'REPOSITORY-CLASSIFICATION.md',
        'SECURITY-BASELINE.md',
      ],
      exclude_prefixes: [],
      exclude_files: [],
      marker: 'Changelog:',
      max_entries: 3,
      why: 'unbounded in-body changelogs are what pushed the real history out of '
        + 'reach in sibling repositories — the newest three belong in the file, '
        + 'the rest belongs to `git log --follow`',
    },

    'version-bump': {
      // Every governed document carries `version:`, so editing one without
      // bumping it is now a detectable defect rather than a matter of memory.
      enabled: true,
    },

    // ---- Phase 2+ content rules ----
    // Deliberately left inert. Each one exists to pin a fact that has ALREADY
    // drifted in this repository — adding entries speculatively is how a
    // config turns into logic. The first real candidate is the exceptions
    // list above, which is restated in docs/org-governance-adoption.md; if it
    // drifts once, it becomes a `facts` entry rather than a manual fix.
  },
};
